name: Hub Aggregator
on:
  push:
    branches:
      - main
jobs:
  Aggregate-Language-Files:
    runs-on: ubuntu-latest
    steps:
      - name: Do the Thing
        uses: cephalofair/rules-actions@v0.1
        with:
          hub-repo: cephalofair/rules-hub

