name: Trigger Hub Update
on:
  push:
    branches:
      - main
jobs:
  Trigger-Hub-Update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Hub Update
        uses: cephalofair/rules-actions/trigger-hub@v0.2
