name: Trigger Hub Update
on:
  push:
    branches:
      - main
jobs:
  Trigger-Hub-Update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Hub Update
        uses: ${{ vars.ACTIONS_REPO }}/trigger-hub@v0.3
        with:
          pat: ${{ secrets.PAT }}
